### ISSUE TITLE
Adding a demo dataset to run muset_pa

### ISSUE THREAD

**Issue by CamilaDuitama** [CamilaDuitama/muset#13]
Could you please upload a demo dataset and show how to run muset_pa with a simple example. It is important as the fof of muset is not the same as the fof file of muset_pa.
Thanks !
https://github.com/CamilaDuitama/muset/blob/ca6a6cd2e2287f23875dee7ab88d05d322f7c99c/README.md?plain=1#L233

**Comment by rvicedomini** [comment]
In the "Input file" subsection was actually explained that input file is different. I rephrased/simplified the paragraph and put a minimal example to run `muset_pa` on the test data.

**Comment by frankandreace** [comment]
Yes I did not upload the fof while waiting to see if we were gonna change the testing structure with Yoann for the reproducibility. Thanks Riccardo for adding the file.

**Comment by frankandreace** [comment]
Thanks Riccardo for adding the fof in the test. I did not push it as I was waiting to see what Yoann was gonna do with the tests. Anyway the rest was explained in the readme.

**Comment by rvicedomini** [comment]
Actually you already put the fof in the test :D 
I just added a brief explanation of the command lines in the readme.
I think that Yoann's tests have a different goal and Camila's concern was more towards being more precise on how to use the command.
