### ISSUE TITLE
Invalid option -u in version v0.4.2

### ISSUE THREAD

**Issue by Fadwa7** [CamilaDuitama/muset#15]
Hello,

Thank you for the great tool! I’m testing Muset using data from Logan. However, I encountered an error when I tried to use the -u option. The tool doesn’t recognize it, and I get the following message:
`[2024-11-21 14:47:55] Invalid option: -u
[2024-11-21 14:47:55] Try 'muset -h' for more information.` 

Could you confirm if this option is integrated by default in the latest version (v0.4.2)?

Thank you in advance for your response.

Best regards,
Fadwa

**Comment by rvicedomini** [comment]
Hello Fadwa,

The `-u` option is currently not available in the main branch (and in v0.4.2 as well).
I am about to release a major update of the whole set of tools, which will integrate the `-u`/`--logan` option and several other improvements (e.g., a probably better output representation).

It should take me 1 or 2 days. I'll keep you posted when available.

Best regards,
Riccardo

**Comment by rvicedomini** [comment]
Version 0.5 has been released and now integrates the `-u` (or, equivalently, `--logan`) option, as well as other changes.

See the [changelog](https://github.com/CamilaDuitama/muset/releases/tag/v0.5) for the full list.

**Comment by Fadwa7** [comment]
Thank You so much for your answer
