### ISSUE TITLE
Parameters are duplicated with kmtricks

### ISSUE THREAD

**Issue by CamilaDuitama** [CamilaDuitama/muset#2]
We should verify that there are parameters that are duplicated with kmtricks, perhaps one filtering (at the beginning) is enough:

- [Minimum count of k-mers to be retained (-c)](https://github.com/CamilaDuitama/kmat_tools/blob/e16db5a4459a9f18c609eb2e3f15fb18a18c1b94/kmer_2_unitig_matrix.sh#L26) in kmtools should be abundance min of kmtricks
- [Minimum number of non-zero columns for each k-mer (-N)](https://github.com/CamilaDuitama/kmat_tools/blob/5bdf64f7cd4ba9ae8925100aaf63d8f6ea1fad70/kmer_2_unitig_matrix.sh#L32) in kmtools is recurrence_min in kmtricks

**Comment by frankandreace** [comment]
I looked at both tools parameters and indeed these are duplicates, given that they are set to the correct value [their default values are different'. So we should just have 1 value for *min_abundance* and *min_recurrence* and set both tools to this value.
1. -c and -a.
* In kmtools filter:  ' -a INT    min abundance to define a k-mer as present in a sample [1]';
* In kmtricks: '--hard-min    - min abundance to keep a k-mer. {2}'.
2.  -N and --recurrence-min. 
* In kmtools filter: ' -N INT    min number of samples for which a k-mer should be present [10]';
* In kmtricks: '--recurrence-min <INT>: All k-mers/hashes that do not occur in at least recurrence-min sample(s) are discarded {1}'.

**Comment by rvicedomini** [comment]
I merged the `-c` and `-a` parameters. More precisely I removed `-c` and only kept `-a`.
I also thought that the default value of this parameter should be 2 as in kmtricks.

I also set to 1 the `-s` parameter of ggcat's call. This must always be 1 as, by construction, input k-mers provided to ggcat are unique.

For reference: https://github.com/CamilaDuitama/muset/commit/2c87ff3ef0df06a24be941bb50e2b0afdaee87dd

**Comment by rvicedomini** [comment]
I was thinking about the `-N` and `-r` parameters which have the same behavior.
Considering that `-F` and `-N` are mutually exclusive, I suggest to set the `--recurrence-min` parameter in `kmtricks` to 1 by default (now is 3) and set it differently only if option `-N` is used. What do you think @CamilaDuitama & @frankandreace ? Was there a particular reason to pick 3 as default value for `--recurrence-min` ?

**Comment by CamilaDuitama** [comment]
I set --recurrence-min to 3 because that was the way decOM's matrix was produced, but it can be set to kmtricks default value @rvicedomini

**Comment by CamilaDuitama** [comment]
btw default minimizer size in kmtricks is 15, not 10 see https://github.com/tlemane/kmtricks/wiki/kmtricks-pipeline

**Comment by rvicedomini** [comment]
Hi @CamilaDuitama & @frankandreace,
I just removed the `-r` parameter. It is now hidden from the user and set to `1` (kmtrick's default). It is set to a different value only if `-N` is used (as we agreed).
